Darya: Homework_3 Done
eokulik/code_or_die pull request #21
Opened 2022-12-01 16:09 UTC by dshurava

2022-12-04 10:19 UTC, eokulik requested changes
Нужно исправить выполнение первого задания, остальное - не влияет на результат.

2022-12-04 10:19 UTC, eokulik commented on Daria/Homework_3/task_1.py
> +print('ing '.join(split_string))
В задании не было написано "избавиться от знаков препинания" ))

2022-12-04 10:19 UTC, eokulik commented on Daria/Homework_3/task_3.py
> +        continue
Можно было не делать `continue`, т.к. кроме `if` в этом цикле ничего нет и когда программа завершит обработку этого условия, ей все равно ничего не останется как пойти на продолжение.

2022-12-04 10:19 UTC, eokulik commented on Daria/Homework_3/task_3.py
> +numbers_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
А что же чисел только 20? ((

2022-12-04 21:22 UTC, dshurava commented on Daria/Homework_3/task_1.py
> +print('ing '.join(split_string))
Да, это импровизация) Пофиксила!

2022-12-06 10:45 UTC, eokulik approved these changes

2022-12-06 10:45 UTC, eokulik commented on Daria/Homework_3/task_1.py
> +print(result)
А ты уже училась где-то питону, да?
Здесь регекспы и `map` не вносят в код простоты и не упрощают работу. Такое решение вполне приемлемо, но простой `for` и проверка на вхождение в условиях (`if word[-1] in (',', '.'):`) было бы вполне достаточно.
Лучше всегда выбирать тот подход, который проще писать и проще читать

2022-12-06 10:45 UTC, merged