amur: homework 3 completed
eokulik/code_or_die pull request #22
Opened 2022-12-02 14:19 UTC by amurKontur

Added homework 3 tasks solutions.

2022-12-04 10:33 UTC, eokulik requested changes
Все работает правильно. Но местами немного перемудрено. А основа питона - это простота. Поправь если будет время.

2022-12-04 10:33 UTC, eokulik commented on amur/Homework_3/Task_1.py
> +new_text = ''.join(list_new_text).lstrip()
вот тут заморочился, конечно. Достаточно
```python
new_text = list_new_text.lstrip()
```
А можно было бы `list_new_text` сделать действительно списком `[]` и тогда на каждом витке цикла допихивать туда `word` с помощью `append`, и тогда в этой строчке джойн был бы оправдан, но не нужно было бы `lstrip`

2022-12-04 10:33 UTC, eokulik commented on amur/Homework_3/Task_3.py
> +        print(number)
Работает правильно. Но есть простой способ проверки делится ли одно число на другое - проверить наличие остатка от деления. В питоне это делается с помощью `%`. Т.е. проверить делится ли число на 3 можно так `if number % 3 == 0`

2022-12-05 13:52 UTC, amurKontur commented on amur/Homework_3/Task_1.py
> +new_text = ''.join(list_new_text).lstrip()
fixed. решил названия поменять чтоб более соответствовало тому что там находится и удалил лишние действия

2022-12-05 13:53 UTC, amurKontur commented on amur/Homework_3/Task_3.py
> +        print(number)
заменил условие на работу с остатком

2022-12-06 10:48 UTC, eokulik approved these changes
Кстати, круто, что ты нашел проверку `isalpha()`, хотя мог бы обойтись поиском точки и запятой. Так код становится более универсальным.

2022-12-06 10:48 UTC, merged