Homework_2 done
eokulik/code_or_die pull request #23
Opened 2022-12-04 17:12 UTC by AnastasiyaZhd

anastasia: homework 2 completed

2022-12-04 17:14 UTC, AnastasiyaZhd commented
Error: The process '/opt/hostedtoolcache/Python/3.10.8/x64/bin/flake8' failed with exit code 1
@eokulik

2022-12-06 10:20 UTC, eokulik requested changes
Перед тем как выполнять это задание, ты не обновила свою ветку `main`, похтому залетели лишние файлы. И тут две вещи: 
* нужно всегда создавать новую ветку из ветки `main`, ветку `main` перед этим нужно обновлять
* нужно контролировать какие файлы комитятся (в пайчарме это легко - при комите убираешь галочки с тех, которые лишние)

2022-12-06 10:20 UTC, eokulik commented on anastasia/homework_2/task_1.py
> +my_dict['str'] = 'Mauris fringilla odio sit amet pretium ultricies. Pellentesque habitant morbi tristique'
Можно было это одним выражением сделать:
```python
my_dict = {'tuple': ('aaa', 111, True, 'qwerty', 222), 'list': ['aaa', 111, True, 'qwerty', 222], итд}
```

2022-12-06 10:20 UTC, eokulik commented on anastasia/homework_2/task_1.py
> +my_dict['dict']['i am a tuple'] = 6
добавьте элемент с ключом `('i am a tuple',)`

2022-12-06 10:20 UTC, eokulik commented on anastasia/homework_2/task_1.py
> +print(my_dict['str'][:7])
вернет буквы с индексами 0,1,2,3,4,5,6 - итого 7

2022-12-06 10:20 UTC, eokulik commented on anastasia/homework_2/task_1.py
> +        print(words.index(word))
Не, превращать в список не нужно. Функцию `index` можно использовать прямо сразу для строки.

2022-12-06 10:58 UTC, AnastasiyaZhd commented on anastasia/homework_2/task_1.py
> +print(my_dict['str'][:7])
ah! "not including"

2022-12-06 11:06 UTC, AnastasiaArts commented on anastasia/homework_2/task_1.py
> +my_dict['str'] = 'Mauris fringilla odio sit amet pretium ultricies. Pellentesque habitant morbi tristique'
aha. I did my way, because there were "1. create dictionary with keys:...", "2. "Add values...". Not "Create dictionary with keys and values"

2022-12-06 11:06 UTC, AnastasiyaZhd commented on anastasia/homework_2/task_1.py
> +my_dict['dict']['i am a tuple'] = 6
fixed

2022-12-06 11:06 UTC, AnastasiyaZhd commented on anastasia/homework_2/task_1.py
> +print(my_dict['str'][:7])
fixed

2022-12-06 11:28 UTC, eokulik commented on anastasia/homework_2/task_1.py
> +my_dict['str'] = 'Mauris fringilla odio sit amet pretium ultricies. Pellentesque habitant morbi tristique'
Я замучался формулировать это задание. Надо было написать как-то так, чтобы было однозначно понятно. Поэтому все по пунктикам ))

2022-12-06 11:29 UTC, eokulik approved these changes

2022-12-06 11:29 UTC, merged