anastasia_homework_4
eokulik/code_or_die pull request #29
Opened 2022-12-09 16:20 UTC by AnastasiaArts

2022-12-13 06:36 UTC, eokulik requested changes
Можешь исправлять - можешь нет. Все рабочее, но местами просто лаконичнее и понятнее можно было сделать.

2022-12-13 06:36 UTC, eokulik commented on anastasia/homework_4/task_1.py
> +bonus = bool(randint(0, 1))
Хитро, но можно было импортнуть еще и `choice` и сделать
```python
bonus = choice([True, False])
```

2022-12-13 06:36 UTC, eokulik commented on anastasia/homework_4/task_1.py
> +salary_with_bonus = int
А для чего эта строчка? Если бы она была нужна, то надо бы сделать `int()`, а еще лучше `salary_with_bonus = 0`, но в случае, когда значение переменной присваивается с помощью `if - else`, то не нужно объявлять пустую переменную перед этим, так как в любом случае она будет назначена. А вот если она назначается с помощью просто `if` или `if - elif` без `else`, то пустую переменную лучше создать, чтобы не оказалось ситуации, когда ты к ней обращаешься, а она не создана.

2022-12-13 06:36 UTC, eokulik commented on anastasia/homework_4/task_1.py
> +    salary_with_bonus = salary + randint(1, 1000)
Ну и зажмотишь же ты кому-то бонуса. Целый +1 бакс добавишь. ))

2022-12-13 06:36 UTC, eokulik commented on anastasia/homework_4/task_2.py
> +for each in dict.items(words):
вместо `dict.items(words)` делается `words.items()`  
И можно сразу разложить на составляющие, что бы потом не приходилось обращаться к ним по позиции
```python
for letter, count in words.items():
    print(letter * count)
```
Так еще и понятнее выглядит

2022-12-13 06:37 UTC, eokulik commented
Если не будешь исправлять, то отпиши об этом

2022-12-13 08:19 UTC, AnastasiaArts commented on anastasia/homework_4/task_1.py
> +    salary_with_bonus = salary + randint(1, 1000)
it's not me - it's random)

2022-12-13 08:28 UTC, AnastasiaArts commented on anastasia/homework_4/task_1.py
> +salary_with_bonus = int
fixed. guess it is leftovers since I didn't have `else` in my algorithm before

2022-12-13 08:28 UTC, AnastasiaArts commented on anastasia/homework_4/task_1.py
> +bonus = bool(randint(0, 1))
will know, thanks

2022-12-13 12:50 UTC, AnastasiaArts commented
that's all fixes from my side @eokulik

2022-12-20 10:00 UTC, eokulik approved these changes

2022-12-20 10:00 UTC, merged