amur: homework 8 completed
eokulik/code_or_die pull request #50
Opened 2023-02-01 12:30 UTC by amurKontur

homework 8 is completed

2023-02-14 07:26 UTC, eokulik requested changes

2023-02-14 07:26 UTC, eokulik commented on amur/homework_8/task_1.py
> +Book.print_book_info(google_testing)
Когда ты создаешь экземпляры объекта (у тебя это `idiot`, `novel_1984`, `algernon_flowers`, `google_testing`), то ты получаешь доступ к свойствам и методам этого объекта, которые описаны в классе. И ты этим воспользовался в строке 26 - обратился к свойству объекта `idiot`. Так же нужно было сделать и с методом `print_book_info`
```python
idiot.print_book_info()
```
То, что ты сделал - это создал 4 новых представителя класса Book, не помещая их в переменную и вызвал у этих представителей метод `print_book_info`, передав внутрь созданных ранее представителей этого класса.

2023-02-14 12:37 UTC, amurKontur commented on amur/homework_8/task_1.py
> +Book.print_book_info(google_testing)
please review

2023-02-26 07:52 UTC, eokulik approved these changes

2023-02-26 07:52 UTC, merged